export interface BAWKInterface {
	audioCtx?: AudioContext;
	children: any[];
	sounds: SoundBuffer;
	formats?: Record<string, string>;
	format?: format;
	gainNode?: GainNode;
	compNode?: DynamicsCompressorNode;
	inputNode?: AudioNode;
	volume?: number;
	position: { x: number; y: number; z: number };
	orientation: { x: number; y: number; z: number };

	init(): void;
	dispose(): void;
	setFormats(formats: Record<string, string>): void;
	detectFormats(): void;
	suspend(): void;
	resume(): void;
	load(url: string, keyname?: string): Promise<void>;
	loadSound(url: string, name: string): Promise<void>;
	loadSprite(url: string): Promise<void>;
	loadSpriteBuffer(url: string, data: any): Promise<AudioBuffer>;
	getAudioBuffer(path: string): Promise<AudioBuffer>;
	request(path: string): Promise<ArrayBuffer>;
	setVolume(vol: number): void;
	getVolume(): number | undefined;
	/**plays a sound of course! */
	play(name: Sounds, node?: AudioNode): AudioBufferSourceNode | void;
	attach(position: { x: number; y: number; z: number }, orientation: { x: number; y: number; z: number }): void;
	detach(): void;
	setPosition(vector: { x: number; y: number; z: number }): void;
	setOrientation(vector: { x: number; y: number; z: number }): void;
	addChild(child: any): void;
	removeChild(child: any): void;
	update(): void;
}


type format = "webm" | "ogg" | "mp3" | (string & {});
type KnownSounds =
	| "ammo"
	| "capture_spatula"
	| "challenge_notify"
	| "death_scream10"
	| "death_scream1"
	| "death_scream2"
	| "death_scream3"
	| "death_scream4"
	| "death_scream5"
	| "death_scream6"
	| "death_scream7"
	| "death_scream8"
	| "death_scream9"
	| "drop_spatula"
	| "grenade_AlienEgg"
	| "grenade_bbros"
	| "grenade_beep"
	| "grenade_bees"
	| "grenade_bloodonade"
	| "grenade_blueshell"
	| "grenade_bumble"
	| "grenade_bwd"
	| "grenade_cellphone"
	| "grenade_coolwhip"
	| "grenade_corrupt"
	| "grenade_CrabRave"
	| "grenade_diablocannon"
	| "grenade_Dove"
	| "grenade_football"
	| "grenade_fusion"
	| "grenade_glitterbomb"
	| "grenade_holy"
	| "grenade_infernal"
	| "grenade_KartBanana"
	| "grenade_Kettlebell"
	| "grenade_Mayan"
	| "grenade_milkbucket"
	| "grenade_milk"
	| "grenade_mort"
	| "grenade"
	| "grenade_octopus"
	| "grenade-oilcan"
	| "grenade_pin"
	| "grenade_Polaroid"
	| "grenade_skullnado"
	| "grenade_Steambot"
	| "grenade_supernova"
	| "grenade_thermal"
	| "grenade_Timebomb"
	| "grenade_tire"
	| "grenade_tp"
	| "grenade_unicorn"
	| "grenade_valkyrie"
	| "grenade_Whip"
	| "grenade_worms"
	| "gun_aug_Cupid_fire"
	| "gun_aug_cycle"
	| "gun_aug_fire"
	| "gun_aug_Fusion_fire"
	| "gun_aug_Infernal_fire"
	| "gun_aug_insert_mag"
	| "gun_aug_Pumpkinpie_fire"
	| "gun_aug_remove_mag"
	| "gun_aug_Retro_fire"
	| "gun_aug_Techno_fire"
	| "gun_aug_Valkyrie_fire"
	| "gun_cluck9mm_Camera_fire"
	| "gun_cluck9mm_Clouds_fire"
	| "gun_cluck9mm_CubicCastles_fire"
	| "gun_cluck9mm_fire"
	| "gun_cluck9mm_Frostfall_fire"
	| "gun_cluck9mm_Fusion_fire"
	| "gun_cluck9mm_Infernal_fire"
	| "gun_cluck9mm_insert_mag"
	| "gun_cluck9mm_Megaphone_fire"
	| "gun_cluck9mm_remove_mag"
	| "gun_cluck9mm_Retro_fire"
	| "gun_cluck9mm_spaceEgg_fire"
	| "gun_cluck9mm_Steambot_fire"
	| "gun_cluck9mm_Techno_fire"
	| "gun_cluck9mm_Valkyrie_fire"
	| "gun_csg1_fire"
	| "gun_csg1_Fusion_fire"
	| "gun_csg1_Infernal_fire"
	| "gun_csg1_pull_action"
	| "gun_csg1_release_action"
	| "gun_csg1_Retro_fire"
	| "gun_csg1_RubberChicken_fire"
	| "gun_csg1_Shellpreme_fire"
	| "gun_csg1_spaceEgg_fire"
	| "gun_csg1_Steambot_fire"
	| "gun_csg1_Techno_fire"
	| "gun_csg1_Valkyrie_fire"
	| "gun_dozenGauge_Basketball_fire"
	| "gun_dozenGauge_Boomstick_fire"
	| "gun_dozenGauge_close"
	| "gun_dozenGauge_Clouds_fire"
	| "gun_dozenGauge_Fantasy_fire"
	| "gun_dozenGauge_fire"
	| "gun_dozenGauge_Fusion_fire"
	| "gun_dozenGauge_Infernal_fire"
	| "gun_dozenGauge_Irish_fire"
	| "gun_dozenGauge_load"
	| "gun_dozenGauge_Octopus_fire"
	| "gun_dozenGauge_open"
	| "gun_dozenGauge_Retro_fire"
	| "gun_dozenGauge_Steambot_fire"
	| "gun_dozenGauge_Techno_fire"
	| "gun_dozenGauge_Valkyrie_fire"
	| "gun_eggk47_Alien_fire"
	| "gun_eggk47_Chocolate_fire"
	| "gun_eggk47_dry_fire"
	| "gun_eggk47_fire"
	| "gun_eggk47_full_cycle"
	| "gun_eggk47_Fusion_fire"
	| "gun_eggk47_Infernal2_fire"
	| "gun_eggk47_Infernal_fire-old"
	| "gun_eggk47_Infernal_fire"
	| "gun_eggk47_insert_mag"
	| "gun_eggk47_remove_mag"
	| "gun_eggk47_Retro_fire"
	| "gun_eggk47_Steambot_fire"
	| "gun_eggk47_Techno_fire"
	| "gun_eggk47_Valkyrie_fire"
	| "gun_m24_Badegg_fire"
	| "gun_m24_bolt_close"
	| "gun_m24_bolt_open"
	| "gun_m24_Chess_fire"
	| "gun_m24_Cyborg_fire"
	| "gun_m24_fire_m24_8bit"
	| "gun_m24_fire"
	| "gun_m24_Fusion_fire"
	| "gun_m24_Infernal_fire"
	| "gun_m24_Quackshot_fire"
	| "gun_m24_Retro_fire"
	| "gun_m24_Scavenger_fire"
	| "gun_m24_Techno_fire"
	| "gun_m24_Valkyrie_fire"
	| "gun"
	| "gun_rpegg_BFG_fire"
	| "gun_rpegg_Bouzouki_fire"
	| "gun_rpegg_Christmas_fire"
	| "gun_rpegg_deny"
	| "gun_rpegg_fire"
	| "gun_rpegg_Fusion_fire"
	| "gun_rpegg_Infernal_fire"
	| "gun_rpegg_load"
	| "gun_rpegg_Retro_fire"
	| "gun_rpegg_rocket_fly"
	| "gun_rpegg_rocket_hit"
	| "gun_rpegg_rocket_poof"
	| "gun_rpegg_Skeleton_fire"
	| "gun_rpegg_Techno_fire"
	| "gun_rpegg_Valkyrie_fire"
	| "gun_smg_Cyborg_fire"
	| "gun_smg_cycle"
	| "gun_smg_fire"
	| "gun_smg_Fusion_fire"
	| "gun_smg_Infernal_fire"
	| "gun_smg_Irish_fire"
	| "gun_smg_Pumpkin_fire"
	| "gun_smg_Retro_fire"
	| "gun_smg_SpecialTurkey_fire"
	| "gun_smg_Techno_fire"
	| "gun_smg_Valkyrie_fire"
	| "hammer_click"
	| "hit"
	| "kotc_capture"
	| "kotc_capturing_opponents"
	| "kotc_capturing_player"
	| "kotc_contested"
	| "kotc_pointscore"
	| "kotc_roundend"
	| "kotc_zonespawn"
	| "melee_banHammer"
	| "melee_bus"
	| "melee_carver"
	| "melee_cup_a"
	| "melee_cup_b"
	| "melee_eggpan"
	| "melee_elf_a"
	| "melee_elf_b"
	| "melee_fan"
	| "melee_fish"
	| "melee_frod"
	| "melee_frostfall"
	| "melee_fryingpan"
	| "melee_fusion"
	| "melee_gfish_a"
	| "melee_gfish_b"
	| "melee_hammer"
	| "melee_harrison-alt"
	| "melee_harrison"
	| "melee_infernal"
	| "melee_kartbros_a"
	| "melee_kartbros_b"
	| "melee_keytar"
	| "melee_mayan"
	| "melee_microphone"
	| "melee_moai"
	| "melee_nutcracker"
	| "melee_pickleball"
	| "melee_plunger"
	| "melee_properfish_a"
	| "melee_properfish_b"
	| "melee_racecar-melee-4"
	| "melee_retro"
	| "melee_rock"
	| "melee_steambot"
	| "melee_techno"
	| "melee_valkyrie"
	| "melee_whip"
	| "melee_whisk_a"
	| "melee_whisk_b"
	| "melee_zombiehand"
	| "mini-egg-game_chick"
	| "mini-egg-game_chirponce"
	| "mini-egg-game_shellburst"
	| "mini-egg-game_shellhit"
	| "mini-egg-game_shial"
	| "mini-egg-game_victory"
	| "pickup"
	| "rooster"
	| "shell_burst"
	| "shellstreak_end"
	| "shellstreak_start"
	| "shield_hit"
	| "ui_chicken"
	| "ui_click"
	| "ui_equip"
	| "ui_onchange"
	| "ui_playconfirm"
	| "ui_popupclose"
	| "ui_popupopen"
	| "ui_reset"
	| "ui_toggletab"
	| "weapon_swap";
type Sounds = KnownSounds | (string & {}); // we know that users can load their own custom sounds, and wont know if they will be updated in the future. therefor we allow any string type

type SoundBuffer = Record<
	string,
	{
		buffer: AudioBuffer;
		start?: number;
		end?: number;
	}
>;
